import { useMemo, useState } from "react";
import { format, subDays } from "date-fns";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { apiClient } from "@/lib/apiClient";
import { Icons } from "@/components/icons";

type SectionKey = "medications" | "bloodPressure" | "bloodSugar" | "diet" | "doctorNotes";

interface HealthReportResponse {
  patient: {
    name: string;
    email: string;
    generated_at: string;
  };
  medications: Array<{
    id: string;
    name: string;
    dosage: string | null;
    strength: string | null;
    frequency: string;
    times: string[];
    instructions: string | null;
  }>;
  medication_adherence: {
    total_doses: number;
    taken: number;
    missed: number;
    adherence_percentage: number;
    per_medication: Array<{
      name: string;
      taken: number;
      missed: number;
      percentage: number;
    }>;
  };
  vitals: {
    latest: {
      bp: string | null;
      sugar: number | null;
      heart_rate: number | null;
      weight: number | null;
    } | null;
    history: Array<{
      id: string;
      systolic: number | null;
      diastolic: number | null;
      blood_sugar: number | null;
      heart_rate: number | null;
      weight: number | null;
      logged_at: string;
      bp_status?: string | null;
      sugar_status?: string | null;
    }>;
    averages: {
      avg_systolic: number | null;
      avg_diastolic: number | null;
      avg_sugar: number | null;
      avg_heart_rate: number | null;
    };
    abnormal_count: number;
  };
  diet: {
    plan_title: string | null;
    doctor_name: string | null;
    created_by: string | null;
    meals: Array<{
      meal_type: string;
      meal_name: string;
      recommended_foods: string;
      avoid_foods: string;
      meal_time: string;
    }>;
    adherence_percentage: number;
    adherence_by_meal_type: Array<{
      meal_type: string;
      total: number;
      followed: number;
      percentage: number;
    }>;
  };
}

interface Props {
  patientId?: string;
  patientName?: string;
  variant?: "card" | "button";
  buttonLabel?: string;
  className?: string;
}

const DEFAULT_SECTIONS: Record<SectionKey, boolean> = {
  medications: true,
  bloodPressure: true,
  bloodSugar: true,
  diet: true,
  doctorNotes: true,
};

const REPORT_RED: [number, number, number] = [180, 44, 56];
const REPORT_DARK: [number, number, number] = [54, 54, 54];
const REPORT_GREEN: [number, number, number] = [34, 139, 94];
const REPORT_YELLOW: [number, number, number] = [217, 143, 41];

function getMedicationFrequencyLabel(frequency: string) {
  const labels: Record<string, string> = {
    once: "1x daily",
    twice: "2x daily",
    three: "3x daily",
    weekly: "Weekly",
    prn: "As needed",
  };
  return labels[frequency] || frequency;
}

function getColorForPercentage(percentage: number) {
  if (percentage < 70) return [180, 44, 56] as const;
  if (percentage <= 85) return [217, 143, 41] as const;
  return [34, 139, 94] as const;
}

function getVitalsBoxColor(value: "good" | "warn" | "bad") {
  if (value === "bad") return [252, 232, 230];
  if (value === "warn") return [254, 243, 199];
  return [220, 252, 231];
}

function formatTimes(times: string[]) {
  if (!times?.length) return "-";
  return times
    .map((time) => {
      const [hours, minutes] = time.split(":").map(Number);
      const period = hours >= 12 ? "PM" : "AM";
      const displayHours = hours % 12 || 12;
      return `${displayHours}:${String(minutes).padStart(2, "0")} ${period}`;
    })
    .join(", ");
}

function addFooter(doc: jsPDF, patientName: string, generatedAt: string) {
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    const width = doc.internal.pageSize.getWidth();
    const height = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...REPORT_RED);
    doc.setLineWidth(0.4);
    doc.line(14, height - 18, width - 14, height - 18);
    doc.setFontSize(9);
    doc.setTextColor(...REPORT_DARK);
    doc.text(patientName, 14, height - 10);
    doc.text(`Page ${page} of ${pageCount}`, width / 2, height - 10, { align: "center" });
    doc.text(`Generated by MedTracker | ${format(new Date(generatedAt), "MMM d, yyyy")}`, width - 14, height - 10, {
      align: "right",
    });
  }
}

function addSummaryBox(doc: jsPDF, x: number, y: number, title: string, value: string, subtitle: string, tone: "good" | "warn" | "bad") {
  doc.setFillColor(...getVitalsBoxColor(tone));
  doc.roundedRect(x, y, 84, 32, 4, 4, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...REPORT_DARK);
  doc.text(title, x + 4, y + 8);
  doc.setFontSize(17);
  doc.text(value, x + 4, y + 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(subtitle, x + 4, y + 26);
}

export function HealthReportExport({
  patientId,
  patientName,
  variant = "card",
  buttonLabel = "Download Health Report",
  className,
}: Props) {
  const [open, setOpen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [from, setFrom] = useState(format(subDays(new Date(), 29), "yyyy-MM-dd"));
  const [to, setTo] = useState(format(new Date(), "yyyy-MM-dd"));
  const [sections, setSections] = useState(DEFAULT_SECTIONS);

  const selectedCount = useMemo(() => Object.values(sections).filter(Boolean).length, [sections]);

  const toggleSection = (key: SectionKey, checked: boolean) => {
    setSections((prev) => ({ ...prev, [key]: checked }));
  };

  const downloadReport = async () => {
    if (selectedCount === 0) {
      toast.error("Select at least one section to include.");
      return;
    }

    setGenerating(true);
    setProgress(10);

    try {
      const query = new URLSearchParams({
        from,
        to,
        ...(patientId ? { patientId } : {}),
      });

      const response = await apiClient.request<{ data: HealthReportResponse; error: { message?: string } | null }>(
        `/report/health-summary?${query.toString()}`
      );

      if (response.error || !response.data) {
        throw new Error(response.error?.message || "Failed to load report data");
      }

      setProgress(35);

      const report = response.data;
      const doc = new jsPDF({ format: "a4", unit: "mm" });
      const width = doc.internal.pageSize.getWidth();
      const height = doc.internal.pageSize.getHeight();
      const periodLabel = `${format(new Date(from), "MMM d")} - ${format(new Date(to), "MMM d, yyyy")}`;

      doc.setFillColor(...REPORT_RED);
      doc.rect(0, 0, width, 46, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(24);
      doc.text("MEDTRACKER", 18, 20);
      doc.setFontSize(18);
      doc.text("Health Report", 18, 30);
      doc.setTextColor(255, 255, 255, 0.1);
      doc.setFontSize(34);
      doc.text("CONFIDENTIAL", width / 2, height / 2, { align: "center", angle: 335 });
      doc.setTextColor(...REPORT_DARK);
      doc.setFontSize(18);
      doc.text(report.patient.name, 18, 66);
      doc.setFontSize(12);
      doc.text(`Patient: ${report.patient.name}`, 18, 79);
      doc.text(`Report Period: ${periodLabel}`, 18, 87);
      doc.text(`Generated: ${format(new Date(report.patient.generated_at), "MMMM d, yyyy")}`, 18, 95);
      doc.setDrawColor(220, 220, 220);
      doc.line(18, 105, width - 18, 105);
      doc.setFontSize(11);
      doc.text("This report is auto-generated", 18, 116);
      doc.text("Share with your doctor", 18, 123);

      setProgress(50);

      doc.addPage();
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...REPORT_DARK);
      doc.setFontSize(18);
      doc.text("Health Summary Overview", 14, 20);

      const bpTone = report.vitals.averages.avg_systolic && report.vitals.averages.avg_diastolic
        ? report.vitals.averages.avg_systolic > 130 || report.vitals.averages.avg_diastolic > 80 ? "bad" : report.vitals.averages.avg_systolic >= 120 ? "warn" : "good"
        : "warn";
      const sugarTone = report.vitals.averages.avg_sugar == null ? "warn" : report.vitals.averages.avg_sugar > 180 || report.vitals.averages.avg_sugar < 70 ? "bad" : "good";
      const medTone = report.medication_adherence.adherence_percentage < 70 ? "bad" : report.medication_adherence.adherence_percentage <= 85 ? "warn" : "good";
      const dietTone = report.diet.adherence_percentage < 60 ? "bad" : report.diet.adherence_percentage <= 80 ? "warn" : "good";

      addSummaryBox(doc, 14, 32, "Medication Adherence", `${report.medication_adherence.adherence_percentage}%`, report.medication_adherence.adherence_percentage > 85 ? "Excellent" : "Needs attention", medTone);
      addSummaryBox(doc, 106, 32, "Avg BP", `${report.vitals.averages.avg_systolic ?? "-"} / ${report.vitals.averages.avg_diastolic ?? "-"}`, bpTone === "good" ? "Normal" : bpTone === "warn" ? "Borderline" : "Abnormal", bpTone);
      addSummaryBox(doc, 14, 72, "Avg Sugar", report.vitals.averages.avg_sugar != null ? `${report.vitals.averages.avg_sugar} mg/dL` : "No data", sugarTone === "good" ? "Normal" : sugarTone === "warn" ? "Watch closely" : "Abnormal", sugarTone);
      addSummaryBox(doc, 106, 72, "Diet Adherence", `${report.diet.adherence_percentage}%`, dietTone === "good" ? "On track" : dietTone === "warn" ? "Improving" : "Needs support", dietTone);

      setProgress(65);

      if (sections.medications) {
        doc.addPage();
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.setTextColor(...REPORT_DARK);
        doc.text("Current Medications", 14, 20);

        autoTable(doc, {
          startY: 28,
          head: [["Medication", "Dosage", "Frequency", "Time", "Adherence"]],
          body: report.medications.map((medication) => {
            const adherence = report.medication_adherence.per_medication.find((item) => item.name === medication.name);
            return [
              medication.name,
              medication.dosage || medication.strength || "-",
              getMedicationFrequencyLabel(medication.frequency),
              formatTimes(medication.times),
              `${adherence?.percentage ?? 0}%`,
            ];
          }),
          theme: "grid",
          headStyles: { fillColor: REPORT_RED, textColor: 255 },
          styles: { fontSize: 9, cellPadding: 2.5 },
          didParseCell: (hookData) => {
            if (hookData.section === "body" && hookData.column.index === 4) {
              const value = Number.parseInt(String(hookData.cell.raw), 10);
              hookData.cell.styles.textColor = getColorForPercentage(value);
            }
          },
        });

        const endY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || 110;
        doc.setFontSize(11);
        doc.setTextColor(...REPORT_DARK);
        doc.text(`Doses taken: ${report.medication_adherence.taken} out of ${report.medication_adherence.total_doses} scheduled`, 14, endY + 10);
        doc.text(`Overall adherence: ${report.medication_adherence.adherence_percentage}%`, 14, endY + 18);
        doc.setFillColor(235, 235, 235);
        doc.roundedRect(14, endY + 24, 170, 6, 3, 3, "F");
        doc.setFillColor(...getColorForPercentage(report.medication_adherence.adherence_percentage));
        doc.roundedRect(14, endY + 24, Math.max(8, 170 * (report.medication_adherence.adherence_percentage / 100)), 6, 3, 3, "F");

        const weekendsMissed = report.medication_adherence.missed > 0
          ? "Most missed doses occurred on weekends."
          : "No missed dose pattern detected during this period.";
        doc.text(weekendsMissed, 14, endY + 38);
      }

      if (sections.bloodPressure || sections.bloodSugar) {
        doc.addPage();
        let currentY = 20;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.text("Vitals History", 14, currentY);
        currentY += 8;

        if (sections.bloodPressure) {
          autoTable(doc, {
            startY: currentY,
            head: [["Date", "Systolic", "Diastolic", "Status"]],
            body: report.vitals.history.map((entry) => [
              format(new Date(entry.logged_at), "MMM d"),
              entry.systolic ?? "-",
              entry.diastolic ?? "-",
              entry.bp_status || "-",
            ]),
            theme: "grid",
            headStyles: { fillColor: REPORT_RED, textColor: 255 },
            styles: { fontSize: 9, cellPadding: 2.5 },
            didParseCell: (hookData) => {
              if (hookData.section === "body") {
                const systolic = Number(hookData.row.raw[1]);
                const diastolic = Number(hookData.row.raw[2]);
                if (systolic > 130 || diastolic > 80) {
                  hookData.cell.styles.textColor = [180, 44, 56];
                }
              }
            },
          });

          const bpEndY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || currentY + 40;
          const sortedBp = report.vitals.history.filter((entry) => entry.systolic != null && entry.diastolic != null);
          const highestBp = [...sortedBp].sort((a, b) => (b.systolic || 0) - (a.systolic || 0))[0];
          const lowestBp = [...sortedBp].sort((a, b) => (a.systolic || 0) - (b.systolic || 0))[0];
          doc.setFontSize(10);
          doc.setTextColor(...REPORT_DARK);
          doc.text(`Average BP: ${report.vitals.averages.avg_systolic ?? "-"} / ${report.vitals.averages.avg_diastolic ?? "-"}`, 14, bpEndY + 8);
          doc.text(`Highest: ${highestBp ? `${highestBp.systolic}/${highestBp.diastolic} on ${format(new Date(highestBp.logged_at), "MMM d")}` : "-"}`, 14, bpEndY + 15);
          doc.text(`Lowest: ${lowestBp ? `${lowestBp.systolic}/${lowestBp.diastolic} on ${format(new Date(lowestBp.logged_at), "MMM d")}` : "-"}`, 14, bpEndY + 22);
          doc.text(`Abnormal readings: ${report.vitals.abnormal_count} out of ${report.vitals.history.length} days`, 14, bpEndY + 29);
          currentY = bpEndY + 40;
        }

        if (sections.bloodSugar) {
          autoTable(doc, {
            startY: currentY,
            head: [["Date", "Sugar (mg/dL)", "Status"]],
            body: report.vitals.history
              .filter((entry) => entry.blood_sugar != null)
              .map((entry) => [format(new Date(entry.logged_at), "MMM d"), entry.blood_sugar, entry.sugar_status || "-"]),
            theme: "grid",
            headStyles: { fillColor: REPORT_RED, textColor: 255 },
            styles: { fontSize: 9, cellPadding: 2.5 },
            didParseCell: (hookData) => {
              if (hookData.section === "body") {
                const sugar = Number(hookData.row.raw[1]);
                if (sugar > 180 || sugar < 70) {
                  hookData.cell.styles.textColor = [180, 44, 56];
                }
              }
            },
          });

          const sugarEndY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || currentY + 30;
          const sugarEntries = report.vitals.history.filter((entry) => entry.blood_sugar != null);
          const highSugar = sugarEntries.filter((entry) => (entry.blood_sugar || 0) > 180).length;
          const lowSugar = sugarEntries.filter((entry) => (entry.blood_sugar || 0) < 70).length;
          doc.setFontSize(10);
          doc.setTextColor(...REPORT_DARK);
          doc.text(`Average: ${report.vitals.averages.avg_sugar ?? "-"} mg/dL`, 14, sugarEndY + 8);
          doc.text(`High readings (>180): ${highSugar} times`, 14, sugarEndY + 15);
          doc.text(`Low readings (<70): ${lowSugar} times`, 14, sugarEndY + 22);

          autoTable(doc, {
            startY: sugarEndY + 30,
            head: [["Date", "Heart Rate", "Weight"]],
            body: report.vitals.history.map((entry) => [
              format(new Date(entry.logged_at), "MMM d"),
              entry.heart_rate != null ? `${entry.heart_rate} bpm` : "-",
              entry.weight != null ? `${entry.weight} kg` : "-",
            ]),
            theme: "grid",
            headStyles: { fillColor: REPORT_RED, textColor: 255 },
            styles: { fontSize: 9, cellPadding: 2.5 },
          });
        }
      }

      if (sections.diet) {
        doc.addPage();
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.setTextColor(...REPORT_DARK);
        doc.text("Recommended Diet Plan", 14, 20);
        if (report.diet.created_by === "doctor" && report.diet.doctor_name) {
          doc.setFillColor(252, 242, 225);
          doc.roundedRect(14, 28, 82, 8, 3, 3, "F");
          doc.setFontSize(10);
          doc.text(`Recommended by Dr. ${report.diet.doctor_name}`, 18, 33.5);
        }

        autoTable(doc, {
          startY: 42,
          head: [["Meal", "Time", "Recommended", "Avoid"]],
          body: report.diet.meals.map((meal) => [
            meal.meal_type,
            meal.meal_time || "-",
            meal.recommended_foods || meal.meal_name,
            meal.avoid_foods || "-",
          ]),
          theme: "grid",
          headStyles: { fillColor: REPORT_RED, textColor: 255 },
          styles: { fontSize: 9, cellPadding: 2.5 },
        });

        const dietEndY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || 90;
        doc.setFontSize(11);
        doc.text(`Overall followed: ${report.diet.adherence_percentage}% of meals this month`, 14, dietEndY + 10);
        const bestMeal = [...report.diet.adherence_by_meal_type].sort((a, b) => b.percentage - a.percentage)[0];
        const leastMeal = [...report.diet.adherence_by_meal_type].sort((a, b) => a.percentage - b.percentage)[0];
        doc.text(`Best followed: ${bestMeal ? `${bestMeal.meal_type} (${bestMeal.percentage}%)` : "-"}`, 14, dietEndY + 18);
        doc.text(`Least followed: ${leastMeal ? `${leastMeal.meal_type} (${leastMeal.percentage}%)` : "-"}`, 14, dietEndY + 26);

        let barY = dietEndY + 36;
        report.diet.adherence_by_meal_type.forEach((item) => {
          doc.setFontSize(10);
          doc.text(item.meal_type, 14, barY);
          doc.setFillColor(235, 235, 235);
          doc.roundedRect(44, barY - 4, 120, 5, 2, 2, "F");
          doc.setFillColor(...getColorForPercentage(item.percentage));
          doc.roundedRect(44, barY - 4, Math.max(5, 120 * (item.percentage / 100)), 5, 2, 2, "F");
          doc.text(`${item.percentage}%`, 170, barY, { align: "right" });
          barY += 12;
        });
      }

      if (sections.doctorNotes) {
        doc.addPage();
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.setTextColor(...REPORT_DARK);
        doc.text("Doctor's Observations", 14, 20);
        doc.setFont("helvetica", "normal");
        let lineY = 34;
        for (let i = 0; i < 10; i += 1) {
          doc.line(14, lineY, width - 14, lineY);
          lineY += 18;
        }
        doc.text("Doctor's Signature: ____________________", 14, height - 42);
        doc.text("Date: ____________________", width - 80, height - 42);
      }

      setProgress(90);
      addFooter(doc, report.patient.name, report.patient.generated_at);
      const safeName = (patientName || report.patient.name).replace(/\s+/g, "_");
      doc.save(`HealthReport_${safeName}_${format(new Date(), "yyyy-MM-dd")}.pdf`);
      setProgress(100);
      toast.success("Health report downloaded.");
      setOpen(false);
    } catch (error) {
      console.error("Error generating health report:", error);
      toast.error(error instanceof Error ? error.message : "Failed to generate health report");
    } finally {
      setGenerating(false);
      setTimeout(() => setProgress(0), 500);
    }
  };

  const trigger = variant === "card" ? (
    <Card className={className}>
      <CardHeader className="pb-3">
        <CardTitle className="text-base flex items-center gap-2">
          <Icons.fileText className="w-4 h-4 text-primary" />
          Export Health Report
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm text-muted-foreground">
          Build a printable medical-style PDF with medications, vitals, blood sugar, diet adherence, and notes for your doctor.
        </p>
        <Button className="w-full">
          <Icons.download className="w-4 h-4 mr-2" />
          {buttonLabel}
        </Button>
      </CardContent>
    </Card>
  ) : (
    <Button className={className}>
      <Icons.fileText className="w-4 h-4 mr-2" />
      {buttonLabel}
    </Button>
  );

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Download Health Report</DialogTitle>
          <DialogDescription>
            Choose the date range and the sections to include before generating the PDF.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="report-from">From</Label>
              <Input id="report-from" type="date" value={from} onChange={(e) => setFrom(e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="report-to">To</Label>
              <Input id="report-to" type="date" value={to} onChange={(e) => setTo(e.target.value)} />
            </div>
          </div>

          <div className="space-y-3 rounded-2xl border border-border/70 p-4">
            <p className="text-sm font-medium text-foreground">Include sections</p>
            {[
              { key: "medications", label: "Medications & Adherence" },
              { key: "bloodPressure", label: "Blood Pressure History" },
              { key: "bloodSugar", label: "Blood Sugar History" },
              { key: "diet", label: "Diet Plan" },
              { key: "doctorNotes", label: "Doctor's Notes Page" },
            ].map((item) => (
              <label key={item.key} className="flex items-center gap-3 text-sm text-foreground">
                <Checkbox
                  checked={sections[item.key as SectionKey]}
                  onCheckedChange={(checked) => toggleSection(item.key as SectionKey, checked === true)}
                />
                {item.label}
              </label>
            ))}
          </div>

          {generating && (
            <div className="space-y-2 rounded-2xl bg-muted/50 p-4">
              <p className="text-sm font-medium text-foreground">Preparing your health report...</p>
              <Progress value={progress} />
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)} disabled={generating}>
            Cancel
          </Button>
          <Button onClick={downloadReport} disabled={generating}>
            {generating ? "Generating..." : "Generate PDF"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
