import { 
  Pill, 
  Clock, 
  AlertTriangle, 
  CheckCircle2, 
  Camera, 
  Plus,
  Calendar,
  TrendingUp,
  Users,
  Settings,
  Home,
  Bell,
  Shield,
  Scan,
  QrCode,
  FileText,
  ChevronRight,
  X,
  Check,
  Heart,
  Activity,
  MoreHorizontal,
  Edit,
  Pause,
  Play,
  Trash2,
  Search,
  MapPin,
  Star,
  Phone,
  Package,
  Download,
  Lock,
  Upload,
  XCircle,
  Timer,
  RefreshCw,
  AlertCircle,
  MessageSquare,
  Info,
  Lightbulb,
  Sparkles,
  Eye,
  Flame,
  Volume2,
  VolumeX,
  Square,
  CircleAlert,
  Copy,
  Fingerprint,
} from "lucide-react";

export const Icons = {
  pill: Pill,
  clock: Clock,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle2,
  camera: Camera,
  plus: Plus,
  calendar: Calendar,
  trending: TrendingUp,
  users: Users,
  settings: Settings,
  home: Home,
  bell: Bell,
  shield: Shield,
  scan: Scan,
  qrCode: QrCode,
  fileText: FileText,
  chevronRight: ChevronRight,
  x: X,
  check: Check,
  heart: Heart,
  activity: Activity,
  moreHorizontal: MoreHorizontal,
  edit: Edit,
  pause: Pause,
  play: Play,
  trash: Trash2,
  search: Search,
  mapPin: MapPin,
  star: Star,
  phone: Phone,
  package: Package,
  download: Download,
  lock: Lock,
  upload: Upload,
  xCircle: XCircle,
  timer: Timer,
  refresh: RefreshCw,
  warning: AlertCircle,
  message: MessageSquare,
  info: Info,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  eye: Eye,
  flame: Flame,
  volume: Volume2,
  volumeX: VolumeX,
  stop: Square,
  alertCircle: CircleAlert,
  copy: Copy,
  fingerprint: Fingerprint,
};

export type IconName = keyof typeof Icons;
